"""trainers new sides

Revision ID: 4bae5ea4a17d
Revises: b844692e15f6
Create Date: 2022-06-11 10:58:27.123949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bae5ea4a17d'
down_revision = 'b844692e15f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainers', sa.Column('check_side', sa.Integer(), nullable=True))
    op.add_column('trainers', sa.Column('ans_side', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainers', 'ans_side')
    op.drop_column('trainers', 'check_side')
    # ### end Alembic commands ###
