"""test 10

Revision ID: 5658cac320c2
Revises: 7d7f8ccef6e1
Create Date: 2022-07-19 12:08:12.916121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5658cac320c2'
down_revision = '7d7f8ccef6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
