"""trainers new sides

Revision ID: 7d8fb40abbaa
Revises: 6707621a75e4
Create Date: 2022-06-20 11:31:23.439724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d8fb40abbaa'
down_revision = '6707621a75e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'creator')
    # ### end Alembic commands ###
    pass


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('creator', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
