"""test 12

Revision ID: 93ddf329b58e
Revises: be0784acc01a
Create Date: 2022-07-19 12:38:40.527712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ddf329b58e'
down_revision = 'be0784acc01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words_to_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words_to_users',
    sa.Column('words', sa.INTEGER(), nullable=True),
    sa.Column('users', sa.INTEGER(), nullable=True),
    sa.Column('learn_state', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['users'], ['users.id'], ),
    sa.ForeignKeyConstraint(['words'], ['words.id'], )
    )
    # ### end Alembic commands ###
