"""добавили тренажеры к уроку 3

Revision ID: b844692e15f6
Revises: 
Create Date: 2022-06-09 11:50:39.536149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b844692e15f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainers_to_lessons',
    sa.Column('trainers', sa.Integer(), nullable=True),
    sa.Column('lessons', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lessons'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['trainers'], ['trainers.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainers_to_lessons')
    op.drop_table('trainers')
    # ### end Alembic commands ###
