"""audio 5 sides

Revision ID: b8f79f977286
Revises: 4bae5ea4a17d
Create Date: 2022-06-12 17:45:18.929027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f79f977286'
down_revision = '4bae5ea4a17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('left_side_audio', sa.String(), nullable=True))
    op.add_column('words', sa.Column('down_side_audio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'down_side_audio')
    op.drop_column('words', 'left_side_audio')
    # ### end Alembic commands ###
