"""test 11

Revision ID: be0784acc01a
Revises: 5658cac320c2
Create Date: 2022-07-19 12:10:46.569314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0784acc01a'
down_revision = '5658cac320c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
