"""hash_token0

Revision ID: f34f448df7da
Revises: 9bc75692bd7d
Create Date: 2022-07-13 07:17:44.005614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34f448df7da'
down_revision = '9bc75692bd7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash_token', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hash_token')
    # ### end Alembic commands ###
